version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - CLAMAV_HOST=localhost  # Change if ClamAV is on a different host
      - CLAMAV_PORT=3310       # Default ClamAV port  